cf_api_url: https://api.curseforge.com/v1
modrinth_api_url: https://api.modrinth.com/v2
cf_api_key: YOUR_API_KEY
modrinth_api_key: YOUR_API_KEY
app_api_key: CREATE_OWN_API_KEY
ntfy_url: https://ntfy.sh/change-this-topic